version: "3"
services:
    redis1:
        image: redis:4.0
        container_name: redis1
        restart: always
        volumes: 
            - ./r1/conf/redis.conf:/usr/local/etc/redis/redis.conf
            - ./r1/data:/data
        ports:
            - "6379:6379"
        command: redis-server /usr/local/etc/redis/redis.conf
