version: "3"
services:
  zoo:
    build: .
    restart: always
    container_name: zoo
    # volumes:
    #   - data:/data
    #   - datalog:/datalog
    ports:
      - "2181:2181"
    expose:
      - "2888"
      - "3888"
    networks:
      - net

networks: 
  net:
    driver: bridge

# volumes:
#   data:
#   datalog: