version: "2"
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.2
    container_name: l1
    restart: always
    ports:
      - "5044:5044"
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./pipeline/:/usr/share/logstash/pipeline/