version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node