version: "3"
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        ports:
            - "33061:3306"
        volumes:
            - ~/mysql/conf.d:/etc/mysql/conf.d
            - ~/mysql/data:/var/lib/mysql
            - ~/mysql/log:/var/log/mysql
        networks:
            - net-nmp
    nginx:
        image: nginx:1.15
        container_name: nginx
        restart: always
        ports:
            - "8000:80"
            - "4430:443"
        volumes:
            - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ~/nginx/conf.d:/etc/nginx/conf.d
            - ~/www:/usr/share/nginx/html
        networks:
            - net-nmp
    php:
        build: .
        container_name: php
        restart: always
        expose:
            - "9000"
        voumes:
            - ~/php/conf/php.ini:
            - ~/www:/var/www/html
