version: "3"
services:
  db:
    image:mysql:5.7
    volumes:
      - /conf:/etc/mysql/conf.d
      - ./db_data:/var/lib/mysql
    restart:always
    environment:
      MYSQL_ROOT_PASSWORD:123456
      MYSQL_DATABASE:sn
      MYSQL_USER:sn
      MYSQL_PASSWORD:123456
    networks:
      - net-nmp
    ports:
      - "3306:3306"

networks:
  net-nmp: