version: "3"
services:
  nginx:
    image: nginx:1.15
    container_name: nmp_nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro
      - ./www:/usr/share/nginx/html:ro
    ports:
      - "8000:80"
    networks: 
      - net
    depends_on: 
      - php-fpm
  php-fpm:
    #image: php:7.2-fpm-alpine
    build: ./php
    container_name: php_fpm
    restart: always
    volumes:
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./www:/var/www/html
    expose:
      - "9000"
    networks: 
      - net
    depends_on: 
      - db1
  db1:
    image: mysql:5.7
    container_name: nmp_db_1
    restart: always
    volumes:
      - ./db1/conf:/etc/mysql/conf.d
      - ./db1/data:/var/lib/mysql
      - ./db1/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "33066:3306"
    expose:
      - "3306"
    networks: 
      - net
  redis:
    image: redis:4.0
    container_name: nmp_redis
    restart: always
    volumes: 
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    expose: 
      - "63791"
    networks: 
      - net
networks: 
  net:
    driver: "bridge"
    