version: '3.1'

services:
  nginx:
    image: nginx:1.15
    container_name: n1
    restart: always
    volumes:
      - ./n1/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./n1/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - blog
  blog:
    image: blog:latest
    container_name: b1
    restart: always
    ports:
      - "8080:8080"
    networks:
      - blog
networks:
    blog:
      driver: "bridge"
