version: '3.1'

services:
  nginx:
    image: nginx:1.15
    container_name: n1
    restart: always
    volumes:
      - ./n1/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./n1/conf.d:/etc/nginx/conf.d:ro
      - ./log:/var/log/nginx
    ports:
      - "80:80"
