version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: es1
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./es1/data:/usr/share/elasticsearch/data
      - ./es1/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
    networks:
      - elknet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    container_name: k1
    restart: always
    ports:
      - "5601:5601"
    volumes:
      - ./k1/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elknet
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.2
    container_name: l1
    restart: always
    ports:
      - "5044:5044"
    volumes:
      - ./l1/config:/usr/share/logstash/config/
      - ./l1/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - elknet

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.7.0
    container_name: b1
    restart: always
    volumes:
      - ""
    networks:
      - elknet


networks:
  elknet:
