version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    # environment:
    #   SERVER_NAME: kibana
    #   ELASTICSEARCH_HOSTS: http://127.0.0.1:9200
    