version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks: 
      - net

networks: 
  net:
    driver: "bridge"
