version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.101
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.101:21811
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
