version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.10.10.103
      KAFKA_ZOOKEEPER_CONNECT: 10.10.10.103:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: sheepkiller/kafka-manager
    restart: always
    ports:
      - 9000:9000
    environment: 
      ZK_HOSTS: 10.10.10.103:2181